// PERSONAL EVENTS
exports.JOIN_ROOM = 'JOIN_ROOM';
exports.SEND_MESSAGE = 'SEND_MESSAGE';
exports.POPULATE_CHAT = 'POPULATE_CHAT';
exports.MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
exports.MESSAGE_FAILED = 'MESSAGE_FAILED';
exports.MAKE_OFFLINE = 'MAKE_OFFLINE';

// GROUP EVENTS
exports.JOIN_GROUP_ROOM = 'JOIN_GROUP_ROOM';
exports.SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE';
exports.POPULATE_GROUP_CHAT = 'POPULATE_GROUP_CHAT';
exports.GROUP_MESSAGE_SUCCESS = 'GROUP_MESSAGE_SUCCESS';
exports.GROUP_MESSAGE_FAILED = 'GROUP_MESSAGE_FAILED';

// POLL EVENTS
exports.CREATE_POLL = 'CREATE_POLL';
exports.CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
exports.CREATE_POLL_FAILED = 'CREATE_POLL_FAILED;';
exports.SEND_VOTE = 'SEND_VOTE';
exports.VOTE_SUCCESS = 'VOTE_SUCCESS';
exports.VOTE_FAILED = 'VOTE_FAILED';

// LIST EVENTS
exports.JOIN_LIST = 'JOIN_LIST';
