exports.JOIN_ROOM = 'JOIN_ROOM';
exports.SEND_MESSAGE = 'SEND_MESSAGE';
// exports.RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
exports.POPULATE_CHAT = 'POPULATE_CHAT';
exports.MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
exports.MESSAGE_FAILED = 'MESSAGE_FAILED';

// GROUP EVENTS
exports.JOIN_GROUP_ROOM = 'JOIN_GROUP_ROOM';
exports.SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE';
// ('RECEIVE_GROUP_MESSAGE');
exports.POPULATE_GROUP_CHAT = 'POPULATE_GROUP_CHAT';
exports.GROUP_MESSAGE_SUCCESS = 'GROUP_MESSAGE_SUCCESS';
exports.GROUP_MESSAGE_FAILED = 'GROUP_MESSAGE_FAILED';
